[package]
name = "gymnasium"
version = "0.1.0"
authors = ["unrenormalizable <unrenormalizable@gmail.com>"]

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
reqwest = { version = "0.11", features = ["blocking", "json"] }
