name: cdp

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches: [master]

jobs:
  build-test-rust:
    name: Build & test rust
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo build (client)
        continue-on-error: false
        run: |
          cd rust/client
          cargo build --release --examples

      - name: Run cargo test (client)
        continue-on-error: false
        run: |
          $job = python gym_http_server.py -g ERROR &
          Start-Sleep 15
          cd rust/client
          cargo test --release
          Stop-Job $job.Id
          Receive-Job $job.Id
        shell: pwsh

      - name: Run cargo build (rl)
        continue-on-error: false
        run: |
          cd rust/rl
          cargo build --release
        shell: pwsh

      - name: Run cargo test (rl)
        continue-on-error: false
        run: |
          cd rust/rl
          cargo test --release
        shell: pwsh

  lint-rust:
    name: Lint rust
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        continue-on-error: false
        run: |
          cd rust/client
          cargo fmt --all -- --check

      - name: Run cargo clippy
        continue-on-error: false
        run: |
          cd rust/client
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Run cargo fmt
        continue-on-error: false
        run: |
          cd rust/rl
          cargo fmt --all -- --check

      - name: Run cargo clippy
        continue-on-error: false
        run: |
          cd rust/rl
          cargo clippy --all-targets --all-features -- -D warnings

  build-test-py:
    name: Build & Test python
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Running tests
        continue-on-error: false
        run: |
          $job = python gym_http_server.py -g ERROR &
          Start-Sleep 15
          nose2
          Stop-Job $job.Id
          Receive-Job $job.Id
        shell: pwsh

  lint-py:
    name: Lint python
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Analysing the code with pylint
        run: |
          pylint *.py **/*.py

      - name: Analysing formatting with black
        run: |
          black --check --diff .

  finish:
    name: Finish
    needs: [build-test-rust, lint-rust, build-test-py, lint-py]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done..."
